/**
 * Authors:  Jephtia, Sebastian
 * Created: Jan 25, 2018
 */

USE BOOKSTORE;

DROP TABLE IF EXISTS BOOK_AUTHORS;
DROP TABLE IF EXISTS INVOICE_DETAILS;
DROP TABLE IF EXISTS MASTER_INVOICES;
DROP TABLE IF EXISTS REVIEWS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS TAXES;

CREATE TABLE BOOKS (
    BOOK_ID int NOT NULL AUTO_INCREMENT,
    ISBN_NUMBER varchar(14) NOT NULL default '',
    TITLE varchar(100) NOT NULL default '',
    PUBLISHER varchar(50) NOT NULL default '',
    PUBLICATION_DATE timestamp default CURRENT_TIMESTAMP,
    PAGE_NUMBER int(5) NOT NULL default 1,
    GENRE varchar(20) NOT NULL default '',
    DESCRIPTION MEDIUMTEXT NOT NULL,
    IMAGE_PATH varchar(100) NOT NULL default '',
    FORMAT varchar(10) NOT NULL default '',
    WHOLESALE_PRICE decimal(5,2) NOT NULL default 0.00,
    LIST_PRICE decimal(5,2) NOT NULL default 0.00,
    SALE_PRICE decimal(5,2) NOT NULL default 0.00,
    INVENTORY_DATE timestamp default CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOK_ID)
) ENGINE=InnoDB;

CREATE TABLE AUTHORS (
    AUTHOR_ID int NOT NULL auto_increment,
    FIRST_NAME varchar(50) NOT NULL default '',
    LAST_NAME varchar(50) NOT NULL default '',
    PRIMARY KEY (AUTHOR_ID)
) ENGINE=InnoDB;

CREATE TABLE BOOK_AUTHORS (
    BOOK_AUTHOR_ID int NOT NULL AUTO_INCREMENT,
    BOOK_ID int NOT NULL,
    AUTHOR_ID int NOT NULL,
    PRIMARY KEY (BOOK_AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
) ENGINE=InnoDB;

CREATE TABLE USERS (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USERNAME varchar(50) NOT NULL UNIQUE default '',
    PASSWORD varchar(50) NOT NULL default '',
    TITLE varchar(50) NOT NULL default '',
    FIRST_NAME varchar(50) NOT NULL default '',
    LAST_NAME varchar(50) NOT NULL default '',
    COMPANY_NAME varchar(50) NOT NULL default '',
    ADDRESS_1 varchar(100) NOT NULL default '',
    ADDRESS_2 varchar(100) NOT NULL default '',
    CITY varchar(20) NOT NULL default '',
    PROVINCE varchar(2) NOT NULL default '',
    COUNTRY varchar(20) NOT NULL default '',
    POSTAL_CODE varchar(6) NOT NULL default '',
    HOME_TELEPHONE varchar(12) NOT NULL default '',
    CELLPHONE varchar(12) NOT NULL default '',
    EMAIL varchar(50) NOT NULL UNIQUE default '',
    IS_MANAGER boolean NOT NULL default FALSE,
    PRIMARY KEY (USER_ID)
) ENGINE=InnoDB;

CREATE TABLE REVIEWS (
    REVIEW_ID int NOT NULL AUTO_INCREMENT,
    BOOK_ID int NOT NULL,
    USER_ID int NOT NULL,
    REVIEW_DATE timestamp NOT NULL default CURRENT_TIMESTAMP,
    RATING int(1) NOT NULL default 1,
    REVIEW MEDIUMTEXT NOT NULL,
    APPROVAL_STATUS boolean NOT NULL default FALSE,
    PRIMARY KEY (REVIEW_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB;

CREATE TABLE MASTER_INVOICES (
    INVOICE_ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    SALE_DATE timestamp NOT NULL default CURRENT_TIMESTAMP,
    NET_VALUE decimal(6,2) NOT NULL default 0.00,
    GROSS_VALUE decimal(6,2) NOT NULL default 0.00,
    PRIMARY KEY (INVOICE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB;

CREATE TABLE INVOICE_DETAILS (
    DETAIL_ID int NOT NULL AUTO_INCREMENT,
    INVOICE_ID int NOT NULL,
    BOOK_ID int NOT NULL,
    BOOK_PRICE decimal(6,2) NOT NULL default 0.00,
    GST_RATE decimal (6,2) NOT NULL default 0.00,
    PST_RATE decimal (6,2) NOT NULL default 0.00,
    HST_RATE decimal (6,2) NOT NULL default 0.00,
    PRIMARY KEY (DETAIL_ID),
    FOREIGN KEY (INVOICE_ID) REFERENCES MASTER_INVOICES(INVOICE_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
) ENGINE=InnoDB;

CREATE TABLE TAXES (
    TAX_ID int NOT NULL AUTO_INCREMENT,
    PROVINCE varchar(2) NOT NULL default '',
    GST_RATE decimal (6,3) NOT NULL default 0.00,
    PST_RATE decimal (6,3) NOT NULL default 0.00,
    HST_RATE decimal (6,3) NOT NULL default 0.00,
    PRIMARY KEY (TAX_ID)
) ENGINE=InnoDB;